name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate Snake Animation
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}  # Uses the repository owner
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
    - name: Commit snake animation
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dist/
        git commit -m "Update snake animation"
        git push
