name: Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate Snake Animation
      uses: Platane/snk@v3
      with:
        targets: 'README.md'
